### ISSUE TITLE
No single `allOf` usage rule

### ISSUE THREAD

**Issue by antonk52** [antonk52/swaggerlint#7]
This rule should help to avoid redundant usage of `allOf`

Example
```yml
DataDTO:
    allOf:
    - type: object
        properties:
            state:
                type: string
            start_date:
                type: string
                format: date
            stop_date:
                type: string
                format: date
```
